Repository LoafThePenguin/LoafThePenguin.Packages, pull requests merged in 2022-12, with the labels that each got.

#5 (chore) Исправление нероботоспособности рабочих процессов.
  .github/workflows/loaf-the-penguin-helpers-release.yml
  .github/workflows/loaf-the-penguin-helpers-sonar-check.yml
Labels: Репозиторий

#6 (chore) Исправление нероботоспособности рабочих процессов.
  .github/workflows/loaf-the-penguin-helpers-release.yml
  .github/workflows/loaf-the-penguin-helpers-sonar-check.yml
Labels: Репозиторий, Релиз

#7 (chore) Исправление работоспособности рабочих процессов.
  .github/workflows/loaf-the-penguin-helpers-release.yml
  .github/workflows/loaf-the-penguin-helpers-sonar-check.yml
Labels: Репозиторий

#11 (chore) Починка работоспособности публикации пакета.
  .github/workflows/loaf-the-penguin-helpers-release.yml
Labels: Репозиторий, Релиз

#13 (chore) Изменение рабочих процессов.
  .github/workflows/loaf-the-penguin-helpers-release.yml
  .github/workflows/loaf-the-penguin-helpers-sonar-check.yml
Labels: Репозиторий, Релиз

#14 (chore) Изменение рабочих процессов.
  .github/workflows/loaf-the-penguin-helpers-release.yml
  .github/workflows/loaf-the-penguin-helpers-sonar-check.yml
Labels: Репозиторий, Релиз

#15 (chore) Изменение логики релиза.
  .github/workflows/loaf-the-penguin-helpers-release.yml
Labels: Репозиторий, Релиз

#17 (chore) Изменение логики релиза.
  .github/workflows/loaf-the-penguin-helpers-release.yml
Labels: Репозиторий, Релиз

#18 (chore) Настройка релиза.
  .github/workflows/loaf-the-penguin-helpers-release.yml
Labels: Репозиторий, Релиз

#19 (chore) Настройка релиза.
  .github/workflows/loaf-the-penguin-helpers-release.yml
Labels: Репозиторий, Релиз

#20 (chore) Починка публикации пакетов.
  .github/workflows/loaf-the-penguin-helpers-release.yml
Labels: Репозиторий, Релиз

#21 (chore) Починка публикации пакетов.
  .github/workflows/loaf-the-penguin-helpers-release.yml
Labels: Репозиторий, Релиз

#23 (chore) Починка публикации пакетов.
  .github/workflows/loaf-the-penguin-helpers-release.yml
Labels: Репозиторий, Релиз

#24 (feat) Добавлена документация методов.
  src/LoafThePenguin.Helpers/Directory.Build.props
  src/LoafThePenguin.Helpers/version.json
Labels: Документация, Нововведение

#25 (feat) Добавлена документация методов.
  src/LoafThePenguin.Helpers/Directory.Build.props
  src/LoafThePenguin.Helpers/version.json
Labels: Документация, Нововведение, Релиз

#28 (chore) Публикация пакетов
  .github/README.md
  .github/workflows/loaf-the-penguin-helpers-release.yml
  .github/workflows/loaf-the-penguin-helpers-sonar-check.yml
  src/LoafThePenguin.Helpers/LoafThePenguin.Helpers.sln
  src/LoafThePenguin.Helpers/docs/README.md
Labels: Репозиторий

#29 Релиз
  .github/README.md
  .github/workflows/loaf-the-penguin-helpers-release.yml
  .github/workflows/loaf-the-penguin-helpers-sonar-check.yml
  src/LoafThePenguin.Helpers/LoafThePenguin.Helpers.sln
  src/LoafThePenguin.Helpers/docs/README.md
Labels: Релиз

#30 (chore) Исправление ошибки авторелиза
  .github/workflows/loaf-the-penguin-helpers-release.yml
  src/LoafThePenguin.Helpers/docs/README.md
Labels: Репозиторий

#31 (chore) Исправление ошибки авторелиза
  .github/workflows/loaf-the-penguin-helpers-release.yml
  src/LoafThePenguin.Helpers/docs/README.md
Labels: Релиз
